import type { EventCalendarI18nOverrides } from "#/components/reui/event-calendar/event-calendar-i18n.tsx"

export const ptI18n: EventCalendarI18nOverrides = {
  labels: {
    today: "Hoje",
    previous: "Anterior",
    next: "Seguinte",
    addEvent: "Adicionar consulta",
    allDay: "Todo o dia",
    more: (count) => `+${count} mais`,
    noEvents: "Sem consultas",
    loading: "A carregar consultas",
    event: "consulta",
    events: (count) => (count === 1 ? "1 consulta" : `${count} consultas`),
    selectView: "Selecionar vista",
    week: (weekNumber) => `S${weekNumber}`,
    resources: "Recursos",
    goToDate: "Ir para data",
    dropNotAllowed: "Não é possível colocar aqui",
    continues: "continua",
    timeFrom: (time) => `A partir das ${time}`,
    timeUntil: (time) => `Até às ${time}`,
    viewShortcuts: {
      month: "M",
      week: "S",
      day: "D",
      days: "5",
      agenda: "A",
      resource: "G",
    },
    toggleDayEvents: (count) => (count === 1 ? "1 consulta" : `${count} consultas`),
    eventDetails: (title) => title,
    moreCompact: (count) => `+${count}`,
    timeRange: (from, to) => `${from} - ${to}`,
  },
  viewNames: {
    month: "Mês",
    week: "Semana",
    day: "Dia",
    days: (count) => (count === 1 ? "1 dia" : `${count} dias`),
    agenda: "Agenda",
    resource: "Grelha horária",
  },
  formats: {
    monthTitle: "MMMM yyyy",
    dayTitle: "EEEE, d 'de' MMMM 'de' yyyy",
    monthDayHeader: "EEE",
    monthDayHeaderNarrow: "EEEEE",
    timeGridDayHeader: "EEE d",
    agendaDayHeader: "EEEE, d 'de' MMMM",
    agendaDayNumber: "d",
    agendaWeekday: "EEE",
    moreDayHeader: "EEEE, d 'de' MMMM",
    monthCellAriaLabel: "PPPP",
    dayAria: "PPPP",
    timeGutter: "HH'h'",
    timeGutterMinute: "HH:mm",
    eventTime: "HH:mm",
    monthCellDay: "d",
  },
}